function RollForAbility()
  print("Rolling For Ability")

    local abilityArray = {
    -- "abaddon_frostmourne",
    -- "axe_counter_helix",
    -- "dragon_knight_frost_breath",
    -- "forged_spirit_melting_strike",
    -- "ghost_frost_attack",
    -- "juggernaut_swift_slash",
    -- "life_stealer_open_wounds",
    -- "lycan_wolf_bite",
    -- "meepo_geostrike",
    -- "ogre_magi_multicast",
    -- "ogre_magi_unrefined_fireblast",
    "phantom_assassin_stifling_dagger",
    -- "treant_eyes_in_the_forest",
    -- "undying_tombstone_zombie_aura",
    -- "undying_tombstone_zombie_deathstrike",
    "abaddon_aphotic_shield",
    "abaddon_borrowed_time",
    "abaddon_frostmourne",
    "abyssal_underlord_atrophy_aura",
    "abyssal_underlord_dark_rift",
    "abyssal_underlord_firestorm",
    "abyssal_underlord_pit_of_malice",
    "alchemist_acid_spray",
    "alchemist_chemical_rage",
    -- "alchemist_goblins_greed",
    "alpha_wolf_command_aura",
    "alpha_wolf_critical_strike",
    -- "ancient_apparition_chilling_touch",
    "ancient_apparition_cold_feet",
    -- "antimage_blink",
    "antimage_mana_break",
    "antimage_mana_void",
    "antimage_spell_shield",
    "arc_warden_magnetic_field",
    "arc_warden_spark_wraith",
    "axe_battle_hunger",
    "axe_berserkers_call",
    "axe_culling_blade",
    "bane_brain_sap",
    "bane_enfeeble",
    "bane_fiends_grip",
    "batrider_firefly",
    "batrider_flaming_lasso",
    "batrider_sticky_napalm",
    "beastmaster_inner_beast",
    "beastmaster_primal_roar",
    "beastmaster_wild_axes",
    "big_thunder_lizard_frenzy",
    "big_thunder_lizard_slam",
    "big_thunder_lizard_wardrums_aura",
    "black_dragon_dragonhide_aura",
    "black_dragon_fireball",
    "bloodseeker_blood_bath",
    "bloodseeker_bloodrage",
    "bloodseeker_rupture",
    -- "bloodseeker_thirst",
    "bounty_hunter_jinada",
    "bounty_hunter_shuriken_toss",
    "bounty_hunter_track",
    "brewmaster_drunken_brawler",
    "brewmaster_drunken_haze",
    "brewmaster_fire_permanent_immolation",
    "brewmaster_primal_split",
    "bristleback_bristleback",
    "bristleback_quill_spray",
    "bristleback_viscous_nasal_goo",
    "bristleback_warpath",
    "broodmother_incapacitating_bite",
    "broodmother_insatiable_hunger",
    "broodmother_spawn_spiderlings",
    "centaur_double_edge",
    "centaur_hoof_stomp",
    "centaur_khan_endurance_aura",
    "centaur_khan_war_stomp",
    "centaur_return",
    "centaur_stampede",
    "chaos_knight_chaos_bolt",
    "chaos_knight_chaos_strike",
    "chaos_knight_phantasm",
    "chaos_knight_reality_rift",
    "chen_holy_persuasion",
    -- "clinkz_burning_army",
    -- "clinkz_searing_arrows",
    "clinkz_strafe",
    "clinkz_wind_walk",
    "crystal_maiden_freezing_field",
    "crystal_maiden_frostbite",
    "dark_seer_ion_shell",
    "dark_seer_vacuum",
    "dark_seer_wall_of_replica",
    "dark_troll_warlord_raise_dead",
    "dark_willow_bedlam",
    "dark_willow_bramble_maze",
    "dark_willow_cursed_crown",
    "dark_willow_shadow_realm",
    "dark_willow_terrorize",
    "dazzle_bad_juju",
    "dazzle_poison_touch",
    "dazzle_shadow_wave",
    "dazzle_shallow_grave",
    "dazzle_weave",
    "death_prophet_carrion_swarm",
    "death_prophet_exorcism",
    "death_prophet_spirit_siphon",
    "disruptor_glimpse",
    "disruptor_kinetic_field",
    "disruptor_static_storm",
    "disruptor_thunder_strike",
    "doom_bringer_doom",
    -- "doom_bringer_infernal_blade",
    "doom_bringer_scorched_earth",
    -- "dragon_knight_dragon_blood",
    "dragon_knight_dragon_tail",
    "dragon_knight_elder_dragon_form",
    -- "drow_ranger_frost_arrows",
    "drow_ranger_marksmanship",
    "drow_ranger_multishot",
    "drow_ranger_wave_of_silence",
    "earth_spirit_rolling_boulder",
    "earthshaker_echo_slam",
    "earthshaker_enchant_totem",
    "earthshaker_fissure",
    "elder_titan_earth_splitter",
    "elder_titan_natural_order",
    "ember_spirit_flame_guard",
    "ember_spirit_searing_chains",
    "ember_spirit_sleight_of_fist",
    "enchantress_enchant",
    -- "enchantress_impetus",
    "enchantress_natures_attendants",
    "enchantress_untouchable",
    "enigma_black_hole",
    "enigma_malefice",
    "enraged_wildkin_toughness_aura",
    "faceless_void_backtrack",
    "faceless_void_chronosphere",
    "faceless_void_time_lock",
    "faceless_void_time_walk",
    "forest_troll_high_priest_heal",
    "forest_troll_high_priest_mana_aura",
    "furion_force_oF_nature",
    -- "furion_teleportation",
    "furion_wrath_of_nature",
    "granite_golem_hp_aura",
    "grimstroke_dark_artistry",
    "grimstroke_ink_creature",
    "grimstroke_soul_chain",
    "grimstroke_spirit_walk",
    "gyrocopter_flak_cannon",
    "harpy_storm_chain_lightning",
    "huskar_berserkers_blood",
    -- "huskar_burning_spear",
    "huskar_inner_fire",
    "huskar_inner_vitality",
    -- "huskar_life_break",
    "jakiro_ice_path",
    -- "jakiro_liquid_fire",
    "jakiro_macropyre",
    "juggernaut_blade_dance",
    "juggernaut_blade_fury",
    "juggernaut_omni_slash",
    "keeper_of_the_light_chakra_magic",
    "keeper_of_the_light_mana_leak",
    "keeper_of_the_light_will_o_wisp",
    "kobold_taskmaster_speed_aura",
    "kunkka_tidebringer",
    "kunkka_torrent_storm",
    "legion_commander_duel",
    "legion_commander_moment_of_courage",
    "legion_commander_overwhelming_odds",
    "legion_commander_press_the_attack",
    "leshrac_diabolic_edict",
    "leshrac_lightning_storm",
    "leshrac_pulse_nova",
    "leshrac_split_earth",
    "lich_chain_frost",
    "lich_frost_shield",
    "lich_sinister_gaze",
    "life_stealer_feast",
    "life_stealer_rage",
    "lina_dragon_slave",
    "lina_fiery_soul",
    "lina_laguna_blade",
    "lina_light_strike_array",
    "lion_finger_of_death",
    "lion_impale",
    "lion_mana_drain",
    "lion_voodoo",
    "lone_druid_rabid",
    "lone_druid_savage_roar",
    "lone_druid_spirit_bear_entangle",
    "lone_druid_spirit_bear",
    "luna_lucent_beam",
    "luna_lunar_blessing",
    "luna_moon_glaive",
    "lycan_feral_impulse",
    "lycan_howl",
    "lycan_shapeshift",
    "lycan_summon_wolves",
    "magnataur_empower",
    "magnataur_reverse_polarity",
    -- "magnataur_skewer",
    "mars_arena_of_blood",
    "mars_bulwark",
    "mars_gods_rebuke",
    "mars_spear",
    -- "medusa_mana_shield",
    "medusa_mystic_snake",
    "medusa_split_shot",
    "medusa_stone_gaze",
    "meepo_ransack",
    "mirana_arrow",
    "mirana_invis",
    -- "mirana_leap",
    "mirana_starfall",
    "monkey_king_boundless_strike",
    "monkey_king_jingu_mastery",
    "morphling_adaptive_strike_agi",
    "morphling_adaptive_strike_str",
    -- "morphling_waveform",
    "mud_golem_hurl_boulder",
    "mudgolem_cloak_aura",
    -- "naga_siren_mirror_image",
    "naga_siren_rip_tide",
    "necrolyte_death_pulse",
    "necrolyte_heartstopper_aura",
    "necrolyte_reapers_scythe",
    "necronomicon_archer_aoe",
    "necronomicon_archer_mana_burn",
    "necronomicon_archer_purge",
    "necronomicon_warrior_last_will",
    "necronomicon_warrior_mana_burn",
    "necronomicon_warrior_sight",
    "nevermore_dark_lord",
    "nevermore_necromastery",
    "night_stalker_hunter_in_the_night",
    "nyx_assassin_impale",
    "nyx_assassin_mana_burn",
    "nyx_assassin_spiked_carapace",
    "nyx_assassin_vendetta",
    -- "obsidian_destroyer_arcane_orb",
    -- "obsidian_destroyer_essence_aura",
    -- "obsidian_destroyer_sanity_eclipse",
    "ogre_magi_bloodlust",
    "ogre_magi_fireblast",
    "ogre_magi_ignite",
    "omniknight_degen_aura",
    "omniknight_guardian_angel",
    "omniknight_repel",
    "oracle_false_promise",
    "oracle_purifying_flames",
    "pangolier_heartpiercer",
    "pangolier_lucky_shot",
    "pangolier_shield_crash",
    -- "pangolier_swashbuckle",
    "phantom_assassin_blur",
    "phantom_assassin_coup_de_grace",
    "phantom_assassin_phantom_strike",
    -- "phantom_lancer_juxtapose",
    -- "phantom_lancer_phantom_edge",
    -- "phantom_lancer_spirit_lance",
    "phoenix_supernova",
    "puck_dream_coil",
    "puck_phase_shift",
    -- "pudge_dismember",
    -- "pudge_flesh_heap",
    "pudge_meat_hook",
    -- "pudge_rot",
    "pugna_decrepify",
    "pugna_life_drain",
    "pugna_nether_blast",
    "pugna_nether_ward",
    "queenofpain_scream_of_pain",
    "queenofpain_shadow_strike",
    "queenofpain_sonic_wave",
    -- "rattletrap_hookshot",
    -- "rattletrap_overclocking",
    "rattletrap_rocket_flare",
    "razor_eye_of_the_storm",
    "razor_plasma_field",
    "razor_static_link",
    "riki_backstab",
    -- "riki_blink_strike",
    "riki_permanent_invisibility",
    "riki_smoke_screen",
    "roshan_slam",
    "roshan_spell_block",
    "rubick_arcane_supremacy",
    "rubick_fade_bolt",
    -- "sandking_burrowstrike",
    "sandking_epicenter",
    "sandking_sand_storm",
    "satyr_hellcaller_shockwave",
    "satyr_hellcaller_unholy_aura",
    "satyr_soulstealer_mana_burn",
    "satyr_trickster_purge",
    "shadow_shaman_ether_shock",
    "shadow_shaman_mass_serpent_ward",
    "shadow_shaman_shackles",
    "shadow_shaman_voodoo",
    "shredder_reactive_armor",
    "shredder_whirling_death",
    -- "silencer_glaives_of_wisdom",
    "silencer_global_silence",
    "silencer_last_word",
    "skeleton_king_hellfire_blast",
    "skeleton_king_mortal_strike",
    "skeleton_king_reincarnation",
    "skeleton_king_vampiric_aura",
    "skywrath_mage_ancient_seal",
    "skywrath_mage_arcane_bolt",
    "skywrath_mage_concussive_shot",
    "skywrath_mage_mystic_flare",
    "slardar_amplify_damage",
    "slardar_bash",
    "slardar_slithereen_crush",
    -- "slardar_sprint",
    "slark_dark_pact",
    "slark_essence_shift",
    -- "slark_pounce",
    "slark_shadow_dance",
    -- "snapfire_firesnap_cookie",
    "snapfire_lil_shredder",
    "snapfire_mortimer_kisses",
    "snapfire_scatterblast",
    "sniper_assassinate",
    "sniper_headshot",
    "sniper_shrapnel",
    "spectre_desolate",
    "spectre_dispersion",
    "spirit_breaker_bulldoze",
    -- "spirit_breaker_charge_of_darkness",
    -- "spirit_breaker_empowering_haste",
    "spirit_breaker_greater_bash",
    "storm_spirit_ball_lightning",
    "storm_spirit_electric_vortex",
    "storm_spirit_overload",
    "sven_gods_strength",
    "sven_great_cleave",
    "sven_storm_bolt",
    "sven_warcry",
    "techies_land_mines",
    "techies_stasis_trap",
    "techies_suicide",
    "templar_assassin_meld",
    "templar_assassin_psi_blades",
    "templar_assassin_refraction",
    -- "terrorblade_conjure_image",
    "terrorblade_metamorphosis",
    "terrorblade_reflection",
    "terrorblade_sunder",
    "tidehunter_anchor_smash",
    "tidehunter_gush",
    "tidehunter_kraken_shell",
    "tidehunter_ravage",
    "tinker_heat_seeking_missile",
    "tinker_laser",
    "tinker_march_of_the_machines",
    "tiny_avalanche",
    -- "tiny_craggy_exterior",
    "tiny_grow",
    "tiny_toss",
    -- "tiny_tree_grab",
    "treant_leech_seed",
    "treant_living_armor",
    "treant_natures_grasp",
    "treant_overgrowth",
    "troll_warlord_battle_trance",
    -- "troll_warlord_berserkers_rage",
    "troll_warlord_fervor",
    "tusk_tag_team",
    "tusk_walrus_kick",
    -- "tusk_walrus_punch",
    "undying_decay",
    "undying_flesh_golem",
    "undying_soul_rip",
    "undying_tombstone",
    "ursa_enrage",
    "ursa_fury_swipes",
    "ursa_overpower",
    "vengefulspirit_magic_missile",
    "vengefulspirit_nether_swap",
    "venomancer_plague_ward",
    "venomancer_poison_nova",
    "venomancer_poison_sting",
    "venomancer_venomous_gale",
    "viper_corrosive_skin",
    "viper_nethertoxin",
    -- "viper_poison_attack",
    "viper_viper_strike",
    "visage_gravekeepers_cloak",
    "visage_soul_assumption",
    "visage_summon_familiars",
    -- "void_spirit_astral_step",
    "warlock_fatal_bonds",
    "warlock_golem_flaming_fists",
    "warlock_golem_permanent_immolation",
    "warlock_shadow_word",
    "weaver_geminate_attack",
    "weaver_shukuchi",
    "weaver_time_lapse",
    "windrunner_focusfire",
    "windrunner_powershot",
    "windrunner_windrun",
    "winter_wyvern_arctic_burn",
    "winter_wyvern_cold_embrace",
    "winter_wyvern_splinter_blast",
    "winter_wyvern_winters_curse",
    "wisp_overcharge",
    -- "wisp_relocate",
    "wisp_tether",
    "witch_doctor_death_ward",
    "witch_doctor_maledict",
    "witch_doctor_paralyzing_cask",
    "witch_doctor_voodoo_restoration",
    "zuus_arc_lightning",
    "zuus_lightning_bolt",
    "zuus_thundergods_wrath",
}

  return abilityArray[ RandomInt( 1, #abilityArray ) ]
end